# Generated by Django 4.2.1 on 2023-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Video title"
                    ),
                ),
                ("href", models.URLField(verbose_name="Url to video")),
                (
                    "is_downloaded",
                    models.BooleanField(default=False, verbose_name="Download status"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        upload_to="preview/%Y/%m/%d/",
                        verbose_name="Preview",
                    ),
                ),
                (
                    "download_url",
                    models.URLField(blank=True, verbose_name="Download url"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="videos/%Y/%m/%d/",
                        verbose_name="Video file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-created_at"],
            },
        ),
    ]
