services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "Qwerty123"
      PGDATA: /data/postgres
    volumes:
       - ./postgresql:/data/postgres
    ports:
      - "5432:5432"
